### ISSUE TITLE
Gliederung der Files nach Usern

### ISSUE THREAD

**Issue by ettka** [OKTOTV/INTAKE#18]
Es wäre schön, wenn sämtliche hochgeladenen Dateien nach den Adressaten geordnet/zusammengefasst werden könnten. So hätte man im "Hauptscreen" der Dateiliste nur die User aufgelistet; mit einem Klick auf eine der Personen werden schließlich die Files sichtbar, die an sie geschickt wurden.

**Comment by SrgSteak** [comment]
Ist mit version 1.2 da. fixed 2fe2a50
