### ISSUE TITLE
VIsuelles Feedback bei Uploads verbessern

### ISSUE THREAD

**Issue by ettka** [OKTOTV/INTAKE#21]
User mit langsamen Internetverbindungen sind sich in der Startphase des Uploads unsicher, ob alles funktioniert. Ein Hinweis wie zB "Upload läuft" wäre sinnvoll.

**Comment by SrgSteak** [comment]
Ich werde den Ladebalken animieren und den Upload Knopf verändern um hier besseres feedback zu gewährleisten. Wie siehts mit einer Prozentanzeige im Ladebalken aus?
