### ISSUE TITLE
Logo für Banner

### ISSUE THREAD

**Issue by ettka** [OKTOTV/INTAKE#30]
Wie besprochen, anbei das Okto Logo plus INTAKE-Schriftzug für den mehrfarbigen Banner unterhalb der Menüleiste.
![okto intake](https://cloud.githubusercontent.com/assets/11075648/8728500/b3e442f0-2be5-11e5-9909-c9b471783de6.png)

Unterhalb des Banners bitte folgenden Begrüßungstext einfügen:
"Okto macht Platz für dich und deine Ideen.
Schön, dass du dein Filmprojekt mit uns und der Welt teilen willst!"

**Comment by SrgSteak** [comment]
Da fehlt das Banner

**Comment by SrgSteak** [comment]
Mein Fehler, ist weiß auf weißem Hintergrund ^^
