### ISSUE TITLE
"Upload erfolgreich"

### ISSUE THREAD

**Issue by ettka** [OKTOTV/INTAKE#32]
Nach einem erfolgreichen Upload soll bitte folgendes Bild mit unten stehendem Text aufscheinen: 

![uploaderfolgreich](https://cloud.githubusercontent.com/assets/11075648/8731479/ecbe3fba-2bf7-11e5-982b-9097611e69d4.png)

Upload erfolgreich!
Vielen Dank für dein Video, unsere MitarbeiterInnen werden in den nächsten Tagen mit dir Kontakt aufnehmen.

**Comment by SrgSteak** [comment]
behoben mit commit 166cb7fc0463186a5a7cef1bc6a66baf35a1b3e6
